FROM golang:1.25-alpine

WORKDIR /src
RUN apk add --no-cache docker-cli git \
    && go install github.com/air-verse/air@v1.61.7
COPY go.mod go.sum ./
RUN go mod download
EXPOSE 8080
CMD ["air", "-c", ".air.toml"]
